### ISSUE TITLE
anaconda hangs on Mac Studio arm64

### ISSUE THREAD

**Issue by FranklinChen** [TalkBank/batchalign#7]
We tried installing batchalign with Anaconda according to the instructions, but the "solve" was taking forever and didn't appear to finish.

**Comment by Jemoka** [comment]
The solve finishes after a while usually. I updated the instruction to recommend the use of mamba which should be quicker: https://github.com/TalkBank/batchalign/commit/18dd3696fcb2e6c09d7666e76f0a8385bd4300fc
